#+OPTIONS: toc:nil
* Stoic
** Marcus Aurelius

#+BEGIN_QUOTE
Waste no more time arguing what a good person should be . Be One.
#+END_QUOTE

#+BEGIN_QUOTE
Think of the life you have lved in until now as over and, as a dead man, see what's left as a bonus and live it according to Nature. Love the hand that fate deals you and play it as your own, for what could be more fitting?
#+END_QUOTE

#+BEGIN_QUOTE
It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinion than our own.
#+END_QUOTE

#+BEGIN_QUOTE
In you actions, don't procrastinate. In you conversations, don't confuse. In you thoughts, don't wander. In you sould, do't be passive or aggresive. In you life, don't be all about business.
#+END_QUOTE

#+BEGIN_QUOTE
If it is not right, do not do it, if it is not true, do not say it.
#+END_QUOTE
** Seneca

#+BEGIN_QUOTE
He who fears death will never do anything worth of a man who is alive.
#+END_QUOTE

#+BEGIN_QUOTE
Life is very short and anxious for those who forget the past, neglect the present, and fear the future
#+END_QUOTE
