#+OPTIONS: toc:nil
* Stoic
** Marcus Aurelius

#+BEGIN_QUOTE
Waste no more time arguing what a good person should be . Be One.
#+END_QUOTE

#+BEGIN_QUOTE
Think of the life you have lved in until now as over and, as a dead man, see what's left as a bonus and live it according to Nature. Love the hand that fate deals you and play it as your own, for what could be more fitting?
#+END_QUOTE

#+BEGIN_QUOTE
It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinion than our own.
#+END_QUOTE

#+BEGIN_QUOTE
In you actions, don't procrastinate. In you conversations, don't confuse. In you thoughts, don't wander. In you sould, do't be passive or aggresive. In you life, don't be all about business.
#+END_QUOTE

#+BEGIN_QUOTE
If it is not right, do not do it, if it is not true, do not say it.
#+END_QUOTE

#+BEGIN_QUOTE
External thinks are not the problem. It’s your assessment of them. Which you can erase right now.
#+END_QUOTE

#+BEGIN_QUOTE
If anyone can refute me—show me I’m making a mistake or looking at things from the wrong perspective—I’ll gladly change. It’s the truth I’m after, and the truth never harmed anyone.
#+END_QUOTE

#+BEGIN_QUOTE
If you are pained by any external thing, it is not this thing that disturbs you, but your own judgment about it. And it is in your power to wipe out this judgment now.
#+END_QUOTE

#+BEGIN_QUOTE
Choose not to be harmed — and you won’t feel harmed. Don’t feel harmed — and you haven’t been.
#+END_QUOTE

#+BEGIN_QUOTE
I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others.
#+END_QUOTE

#+BEGIN_QUOTE
It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinion than our own.
#+END_QUOTE

#+BEGIN_QUOTE
You could leave life right now. Let that determine what you do and say and think.
#+END_QUOTE

#+BEGIN_QUOTE
It’s time you realized that you have something in you more powerful and miraculous than the things that affect you and make you dance like a puppet.
#+END_QUOTE

#+BEGIN_QUOTE
The best revenge is not to be like your enemy.
#+END_QUOTE

#+BEGIN_QUOTE
The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.
#+END_QUOTE

#+BEGIN_QUOTE
Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.
#+END_QUOTE

#+BEGIN_QUOTE
If it is not right, do not do it, if it is not true, do not say it.
#+END_QUOTE

#+BEGIN_QUOTE
Think of the life you have lived until now as over and, as a dead man, see what’s left as a bonus and live it according to Nature. Love the hand that fate deals you and play it as your own, for what could be more fitting?
#+END_QUOTE

#+BEGIN_QUOTE
Time is like a river made up of the events which happen, and a violent stream; for as soon as a thing has been seen, it is carried away, and another comes in its place, and this will be carried away too.
#+END_QUOTE

#+BEGIN_QUOTE
You have power over your mind—not outside events. Realize this, and you will find strength.
#+END_QUOTE

#+BEGIN_QUOTE
Remember: Matter. How tiny your share of it. Time. How brief and fleeting your allotment of it. Fate. How small a role you play in it.
#+END_QUOTE

#+BEGIN_QUOTE
In your actions, don’t procrastinate. In your conversations, don’t confuse. In your thoughts, don’t wander. In your soul, don’t be passive or aggressive. In your life, don’t be all about business.
#+END_QUOTE

#+BEGIN_QUOTE
Whatever happens to you has been waiting to happen since the beginning of time. The twining strands of fate wove both of them together.
#+END_QUOTE

#+BEGIN_QUOTE
Be tolerant with others and strict with yourself.
#+END_QUOTE

#+BEGIN_QUOTE
Asia and Europe: distant recesses of the universe. The ocean: a drop of water. Mount Athos: a molehill. The present: a split second in eternity. Minuscule, transitory, insignificant.
#+END_QUOTE

#+BEGIN_QUOTE
[It is] like seeing roasted meat and other dishes in front of you and suddenly realizing: This is a dead fish. A dead bird. A dead pig. Or that this noble vintage [wine] is rotted grapes… perceptions like that… latching onto things and piercing through them, to see what they really are… to strip away the legend that encrusts them.
#+END_QUOTE

#+BEGIN_QUOTE
The tranquility that comes when you stop caring what they say. Or think, or do. Only what you do.
#+END_QUOTE

#+BEGIN_QUOTE
Things stand outside of us, themselves by themselves, neither knowing anything of themselves nor expressing any judgment.
#+END_QUOTE

#+BEGIN_QUOTE
Because a thing seems difficult for you, do not think it impossible for anyone to accomplish.
#+END_QUOTE

#+BEGIN_QUOTE
Today I escaped from anxiety. Or no, I discarded it, because it was within me, in my own perceptions — not outside.
#+END_QUOTE

#+BEGIN_QUOTE
Plato has a fine saying, that he who would discourse of man should survey, as from some high watchtower, the things of earth.
#+END_QUOTE

#+BEGIN_QUOTE
You can discard most of the junk that clutters your mind…and clear out space for yourself… by comprehending the scale of the world… by contemplating infinite time… by thinking of the speed with which things change — each part of every thing; the narrow space between our birth and death; the infinite time before; the equally unbounded time that follows.
#+END_QUOTE
** Seneca

#+BEGIN_QUOTE
He who fears death will never do anything worth of a man who is alive.
#+END_QUOTE

#+BEGIN_QUOTE
Life is very short and anxious for those who forget the past, neglect the present, and fear the future
#+END_QUOTE

#+BEGIN_QUOTE
No person has the power to have everything they want, but it is in their power not to want what they don’t have, and to cheerfully put to good use what they do have.
#+END_QUOTE

#+BEGIN_QUOTE
Life is very short and anxious for those who forget the past, neglect the present, and fear the future.
#+END_QUOTE

#+BEGIN_QUOTE
Cling tooth and nail to the following rule: not to give in to adversity, never to trust prosperity, and always take full note of fortune’s habit of behaving just as she pleases, treating her as if she were actually going to do everything it is in her power to do. Whatever you have been expecting for some time comes as less of a shock.
#+END_QUOTE

#+BEGIN_QUOTE
Nothing, to my way of thinking, is a better proof of a well ordered mind than a man’s ability to stop just where he is and pass some time in his own company.
#+END_QUOTE

#+BEGIN_QUOTE
You live as if you were destined to live forever, no thought of your frailty ever enters your head, of how much time has already gone by you take no heed. You squander time as if you drew from a full and abundant supply, though all the while that day which you bestow on some person or thing is perhaps your last.
#+END_QUOTE

#+BEGIN_QUOTE
Difficulties strengthen the mind, as labor does the body.
#+END_QUOTE

#+BEGIN_QUOTE
People are frugal in guarding their personal property; but as soon as it comes to squandering time they are most wasteful of the one thing in which it is right to be stingy.
#+END_QUOTE

#+BEGIN_QUOTE
It’s not because things are difficult that we dare not venture. It’s because we dare not venture that they are difficult.
#+END_QUOTE

#+BEGIN_QUOTE
We suffer more often in imagination than in reality.
#+END_QUOTE

#+BEGIN_QUOTE
This is our big mistake: to think we look forward to death. Most of death is already gone. Whatever time has passed is owned by death.
#+END_QUOTE

#+BEGIN_QUOTE
We are more often frightened than hurt; and we suffer more in imagination than in reality.
#+END_QUOTE

#+BEGIN_QUOTE
The mind that is anxious about future events is miserable.
#+END_QUOTE

#+BEGIN_QUOTE
If you really want to escape the things that harass you, what you’re needing is not to be in a different place but to be a different person.
#+END_QUOTE

#+BEGIN_QUOTE
I judge you unfortunate because you have never lived through misfortune. You have passed through life without an opponent—no one can ever know what you are capable of, not even you.
#+END_QUOTE

#+BEGIN_QUOTE
If a man knows not which port he sails, no wind is favorable.
#+END_QUOTE

#+BEGIN_QUOTE
He who fears death will never do anything worth of a man who is alive.
#+END_QUOTE

#+BEGIN_QUOTE
How does it help…to make troubles heavier by bemoaning them?
#+END_QUOTE

#+BEGIN_QUOTE
As long as you live, keep learning how to live. to err is human, but to persist (in the mistake) is diabolical.
#+END_QUOTE

#+BEGIN_QUOTE
A gem cannot be polished without friction, nor a man without trials.
#+END_QUOTE

#+BEGIN_QUOTE
It is the quality rather than the quantity that matters.
#+END_QUOTE

#+BEGIN_QUOTE
Floods will rob us of one thing, fire of another. These are conditions of our existence which we cannot change. What we can do is adopt a noble spirit, such a spirit as befits a good person, so that we may bear up bravely under all that fortune sends us and bring our wills into tune with nature’s.
#+END_QUOTE

#+BEGIN_QUOTE
It does not matter what you bear, but how you bear it.
#+END_QUOTE

#+BEGIN_QUOTE
Let us meet with bravery whatever may befall us. Let us never feel a shudder at the thought of being wounded or of being made a prisoner, or of poverty or persecution.
#+END_QUOTE

#+BEGIN_QUOTE
The whole future lies in uncertainty: live immediately.
#+END_QUOTE

#+BEGIN_QUOTE
Fate leads the willing, and drags along the reluctant.
#+END_QUOTE
** Epictetus

#+BEGIN_QUOTE
Appearances to the mind are of four kinds. Things either are what they appear to be; or they neither are, nor appear to be; or they are, and do not appear to be; or they are not, and yet appear to be. Rightly to aim in all these cases is the wise man’s task.
#+END_QUOTE

#+BEGIN_QUOTE
How long are you going to wait before you demand the best for yourself?
#+END_QUOTE

#+BEGIN_QUOTE
Don’t explain your philosophy. Embody it.
#+END_QUOTE

#+BEGIN_QUOTE
First say to yourself what you would be; and then do what you have to do.
#+END_QUOTE

#+BEGIN_QUOTE
It’s something like going on an ocean voyage. What can I do? Pick the captain, the boat, the date, and the best time to sail. But then a storm hits… What are my options? I do the only thing I am in a position to do, drown — but fearlessly, without bawling or crying out to God, because I know that what is born must also die.
#+END_QUOTE

#+BEGIN_QUOTE
No great thing is created suddenly, any more than a bunch of grapes or a fig. If you tell me that you desire a fig, I answer that there must be time. Let it first blossom, then bear fruit, then ripen.
#+END_QUOTE

#+BEGIN_QUOTE
If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, ‘He was ignorant of my other faults, else he would have not mentioned these alone.
#+END_QUOTE

#+BEGIN_QUOTE
Anything or anyone capable of angering you becomes your master.
#+END_QUOTE

#+BEGIN_QUOTE
That’s why the philosophers warn us not to be satisfied with mere learning, but to add practice and then training. For as time passes we forget what we learned and end up doing the opposite, and hold opinions the opposite of what we should.
#+END_QUOTE

#+BEGIN_QUOTE
It’s not what happens to you, but how you react to it that matters.
#+END_QUOTE

#+BEGIN_QUOTE
Difficulty shows what men are. Therefore when a difficulty falls upon you, remember that God, like a trainer of wrestlers, has matched you with a rough young man. Why? So that you may become an Olympic conqueror, but it is not accomplished without sweat.
#+END_QUOTE

#+BEGIN_QUOTE
Wealth consists not in having great possessions, but in having few wants.
#+END_QUOTE

#+BEGIN_QUOTE
Don’t just say you have read books. Show that through them you have learned to think better, to be a more discriminating and reflective person.
#+END_QUOTE

#+BEGIN_QUOTE
Don’t seek for everything to happen as you wish it would, but rather wish that everything happens as it actually will—then your life will flow well.
#+END_QUOTE

#+BEGIN_QUOTE
Take a lyre player: he’s relaxed when he performs alone, but put him in front of an audience, and it’s a different story, no matter how beautiful his voice or how well he plays the instrument. Why? Because he not only wants to perform well, he wants to be well received — and the latter lies outside his control.
#+END_QUOTE

#+BEGIN_QUOTE
Curb your desire—don’t set your heart on so many things and you will get what you need.
#+END_QUOTE

#+BEGIN_QUOTE
We should always be asking ourselves: “Is this something that is, or is not, in my control?
#+END_QUOTE

#+BEGIN_QUOTE
Books are the training weights of the mind. They are very helpful, but it would be a bad mistake to suppose that one has made progress simply by having internalized their contents.
#+END_QUOTE

#+BEGIN_QUOTE
Just keep in mind: the more we value things outside our control, the less control we have.
#+END_QUOTE

#+BEGIN_QUOTE
Define for me now what the “indifferents” are. Whatever things we cannot control. Tell me the upshot. They are nothing to me.
#+END_QUOTE
** Zeno of Citium
#+BEGIN_QUOTE
Man conquers the world by conquering himself.
#+END_QUOTE
** Heraclitus
#+BEGIN_QUOTE
To be even minded is the greatest virtue.
#+END_QUOTE
** Diogenes
#+BEGIN_QUOTE
He has the most who is content with the least.
#+END_QUOTE
** Cato
#+BEGIN_QUOTE
I begin to speak only when I'm certain what I'll say isn't better left unsaid.
#+END_QUOTE
